language: go
go_import_path: github.com/Shyp/rickover

go:
  - 1.5
  - 1.6
  - 1.7
  - 1.8
  - tip

script: make lint race-test bench

before_script:
  - make test-install
  - go get github.com/kevinburke/goose/cmd/goose
  - goose --env=travis up

addons:
  postgresql: "9.5"

services:
  - postgresql

dist: trusty
