language: go
go_import_path: github.com/kevinburke/rickover

go:
  - 1.9.x
  - 1.10.x
  - 1.11.x
  - master

dist: trusty
sudo: false

script: make lint race-test bench

before_script:
  - make test-install
  - go get -u github.com/kevinburke/goose/cmd/goose
  - goose --env=travis up

env:
  global:
    - TZ=UTC

addons:
  postgresql: "9.6"

services:
  - postgresql

cache:
  directories:
    - $GOPATH/pkg
