language: go

go:
  - 1.5
  - 1.6
  - tip

script: make race-test

before_script:
  - make test-install
  - go get github.com/kevinburke/goose/cmd/goose
  - goose --env=travis up

addons:
  postgresql: "9.4"

services:
  - postgresql
