name: tests
on: [push, pull_request]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    container: meterup/ubuntu-golang

    steps:
    - uses: actions/checkout@master
      with:
         path: './src/github.com/kevinburke/rickover'
    # staticcheck needs this for GOPATH
    - run: echo "GOPATH=$GITHUB_WORKSPACE" >> $GITHUB_ENV
    - run: echo "PATH=$GITHUB_WORKSPACE/bin:$PATH" >> $GITHUB_ENV

    - uses: actions/cache@master
      with:
        path: /go/bin
        key: ${{ runner.os }}-gobin-v1-${{ hashFiles('**/Gopkg.lock') }}
        restore-keys: |
          ${{ runner.os }}-gobin-v1-
    - uses: actions/cache@master
      with:
        path: /github/home/.cache
        key: ${{ runner.os }}-go-v1-${{ hashFiles('**/Gopkg.lock') }}
        restore-keys: |
          ${{ runner.os }}-go-v1-

    - name: Start Postgres, install Goose, migrate database
      run: envdir envs/github make migrate-ci
      working-directory: ./src/github.com/kevinburke/rickover

    - name: Lint
      run: envdir envs/github make lint
      working-directory: ./src/github.com/kevinburke/rickover

    - name: Test rickover
      # github env has correct database URL
      run: envdir envs/github go test -p=1 -race -timeout 10s ./...
      working-directory: ./src/github.com/kevinburke/rickover

    - name: Run benchmarks
      run: envdir envs/github make benchmark-ci
      working-directory: ./src/github.com/kevinburke/rickover
